### ISSUE TITLE
PyPi Update Needed

### ISSUE THREAD

**Issue by joshkersey** [piotrkilczuk/django-inline-ordering#11]
The distro on PyPi is still using the version with the /media/ directory instead of /static/.  Using `pip install django-inline-ordering` leaves Django 1.3+ unable to collect the static file.

**Comment by piotrkilczuk** [comment]
Yes, that is right - thank you for reporting. 

I've put that on my todo, but contributions are welcome.

**Comment by piotrkilczuk** [comment]
OK, uploaded 1.0.0. to pypi. Please report any bugs found.
