### ISSUE TITLE
Does not work with a ManyToMany relationship

### ISSUE THREAD

**Issue by robnewman** [piotrkilczuk/django-inline-ordering#13]
This plugin only appears to work if you have a one-to-many (ForeignKey) relationship between Gallery and Images.

What if you have many Images that you use across different Gallerys (ie. a many-to-many field?). Using your example of Images and Gallery.

This will work:

```
class Gallery(models.Model):
    images = ForeignKey(Image)
```

This won't:

```
class Gallery(models.Model):
    images = ManyToManyField(Image)
```

I have the second setup, and I get the following error when implementing your code:

```
<class 'appname.models.Image'> has no ForeignKey to <class 'appname.models.Gallery'>
```

Maybe I have it set up incorrectly, but I followed your steps exactly.

**Comment by piotrkilczuk** [comment]
Hello Rob,

I think it would rather work the other way around:

```
class Image(models.Model):
    gallery = ForeignKey(Gallery)
```

Anyway, M2M relations are not supported by this lib. Taking into consideration the amount of work required to implement this, I'm not planning to add this functionality to django-inline-ordering (if an image can belong to many galleries, then it can have different position in each one of them).

Cheers,
Piotr
