### ISSUE TITLE
README: Name in INSTALLED_APPS

### ISSUE THREAD

**Issue by pauchocron** [piotrkilczuk/django-inline-ordering#3]
Right now the README says:
"Add 'inline-ordering' to INSTALLED_APPS tuple in settings file"

I think it should be 'inline_ordering'. It won't work otherwise.

**Comment by piotrkilczuk** [comment]
Sure, thanks, I have README an update lying in somewhere...

**Comment by piotrkilczuk** [comment]
Committed.
