### ISSUE TITLE
Wrong positions after deleting inline instances

### ISSUE THREAD

**Issue by c4traz** [piotrkilczuk/django-inline-ordering#6]
I found using Max() to determine the next position will bring in wrong values as soon as an instance with a position < Max() is deleted. Those gaps will not be closed by moving the existing ones one position back.
Therefore I'm doing the saving like this in the ModelAdmin (no custom save() method in the model itself anymore) :

class OrderableAdmin(admin.ModelAdmin):
    def save_formset(self, request, form, formset, change):

```
    instances = formset.save(commit = False)
    nextPos = len(formset.queryset)

    for i in instances:

        if i.inline_ordering_position == None:
            i.inline_ordering_position = nextPos
            nextPos += 1

        i.save()


    formset.save_m2m()
```

**Comment by piotrkilczuk** [comment]
You are right. This is not really a big headache, since position is used only for db-ordering and it is generally considered a 'transparent' field. I will look into this anyway. Thanks!

**Comment by piotrkilczuk** [comment]
Are you sure that the existing ones would be moved up? I can't see code for that...
